services:
  postgres-sql:
    image: postgres
    hostname: "postgres"
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
